name: Publish Home Assistant Docker images

on:
  push

jobs:
  publish:
    name: Build and publish image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
      - name: Publish
        uses: home-assistant/builder@master
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        with:
          args: |
            --all \
            --target python-webhook-pubsub \
            --docker-hub $DOCKER_USERNAME \
            --image pub-sub
